### ISSUE TITLE
Support v5.9.0

### ISSUE THREAD

**Issue by craftzdog** [Daiki48/inkdrop-terracecat-dark-ui-theme#2]
Hi Daiki-san! How are you?

As you may know, the new beta version got a new CSS-variable-based theming system, which makes theming significantly easier:

- Release notes: https://forum.inkdrop.app/t/inkdrop-desktop-v5-9-0-beta-1/5017

To stay compatible with future releases, existing UI themes will need some updates.

I’ve also refreshed the theming guide to walk you through the changes:

- https://developers.inkdrop.app/guides/create-a-theme

Could you take a look and update this theme?
Thank you so much for contributing such a beautiful theme! ❤️
If you have any questions or run into any issues, feel free to comment here.

**Comment by Daiki48** [comment]
@craftzdog Thank you for the notification 👍 

I will refer to the docs and respond to the upgrade 🔧

**Comment by Daiki48** [comment]
@craftzdog 
Supports [v1.0.0](https://github.com/Daiki48/inkdrop-terracecat-dark-ui-theme/releases/tag/v1.0.0)

The work was written in Inkdrop.  
[Inkdrop theme to be compatible with v5.9.0](https://community.inkdrop.app/62dd5c75cb78e1bfaa6ef205adb198ed/4R-hWV3QZ) 

Documentation was extensive. Thank you 🙇‍♂️

**Comment by craftzdog** [comment]
Awesome!! Thank you so much for taking the time to update this theme ✨🙏
Glad the docs were helpful!

**Comment by craftzdog** [comment]
You can publish it to the plugin registry.

**Comment by craftzdog** [comment]
oh it's already up! thanks
